## This is a docker file
## Run the following command in the directory where index.html resides
## docker build -t snakegame:v1.0 .

FROM httpd:2.4

# COPY ./home/psshri/Documents/tech/upSkill/webDev/learn_webDev/snakeGame/ /usr/local/apache2/htdocs/

COPY . /usr/local/apache2/htdocs/